package com.coinbkt.medmyth.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.coinbkt.medmyth.db.FMLibrary;

import com.coinbkt.medmyth.db.FMLibraryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig fMLibraryDaoConfig;

    private final FMLibraryDao fMLibraryDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        fMLibraryDaoConfig = daoConfigMap.get(FMLibraryDao.class).clone();
        fMLibraryDaoConfig.initIdentityScope(type);

        fMLibraryDao = new FMLibraryDao(fMLibraryDaoConfig, this);

        registerDao(FMLibrary.class, fMLibraryDao);
    }
    
    public void clear() {
        fMLibraryDaoConfig.clearIdentityScope();
    }

    public FMLibraryDao getFMLibraryDao() {
        return fMLibraryDao;
    }

}
