package com.coinbkt.medmyth.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "FMLibrary".
*/
public class FMLibraryDao extends AbstractDao<FMLibrary, Long> {

    public static final String TABLENAME = "FMLibrary";

    /**
     * Properties of entity FMLibrary.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "ID");
        public final static Property ThumbImg = new Property(1, Integer.class, "thumbImg", false, "THUMB_IMG");
        public final static Property Img = new Property(2, Integer.class, "img", false, "IMG");
        public final static Property Category = new Property(3, String.class, "category", false, "CATEGORY");
        public final static Property Title = new Property(4, String.class, "title", false, "TITLE");
        public final static Property Desc = new Property(5, String.class, "desc", false, "DESC");
    }


    public FMLibraryDao(DaoConfig config) {
        super(config);
    }
    
    public FMLibraryDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"FMLibrary\" (" + //
                "\"ID\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"THUMB_IMG\" INTEGER," + // 1: thumbImg
                "\"IMG\" INTEGER," + // 2: img
                "\"CATEGORY\" TEXT," + // 3: category
                "\"TITLE\" TEXT," + // 4: title
                "\"DESC\" TEXT);"); // 5: desc
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"FMLibrary\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, FMLibrary entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer thumbImg = entity.getThumbImg();
        if (thumbImg != null) {
            stmt.bindLong(2, thumbImg);
        }
 
        Integer img = entity.getImg();
        if (img != null) {
            stmt.bindLong(3, img);
        }
 
        String category = entity.getCategory();
        if (category != null) {
            stmt.bindString(4, category);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(5, title);
        }
 
        String desc = entity.getDesc();
        if (desc != null) {
            stmt.bindString(6, desc);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, FMLibrary entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer thumbImg = entity.getThumbImg();
        if (thumbImg != null) {
            stmt.bindLong(2, thumbImg);
        }
 
        Integer img = entity.getImg();
        if (img != null) {
            stmt.bindLong(3, img);
        }
 
        String category = entity.getCategory();
        if (category != null) {
            stmt.bindString(4, category);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(5, title);
        }
 
        String desc = entity.getDesc();
        if (desc != null) {
            stmt.bindString(6, desc);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public FMLibrary readEntity(Cursor cursor, int offset) {
        FMLibrary entity = new FMLibrary( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // thumbImg
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // img
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // category
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // title
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // desc
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, FMLibrary entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setThumbImg(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setImg(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setCategory(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setTitle(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setDesc(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(FMLibrary entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(FMLibrary entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(FMLibrary entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
