package com.coinbkt.medmyth.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "FMLIBRARY".
 */
@Entity
public class FMLibrary {

    @Id(autoincrement = true)
    private Long id;
    private Integer thumbImg;
    private Integer img;
    private String packName;
    private String category;
    private String title;
    private String desc;
    private String status;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public FMLibrary() {
    }

    public FMLibrary(Long id) {
        this.id = id;
    }

    @Generated
    public FMLibrary(Long id, Integer thumbImg, Integer img, String packName, String category, String title, String desc, String status) {
        this.id = id;
        this.thumbImg = thumbImg;
        this.img = img;
        this.packName = packName;
        this.category = category;
        this.title = title;
        this.desc = desc;
        this.status = status;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getThumbImg() {
        return thumbImg;
    }

    public void setThumbImg(Integer thumbImg) {
        this.thumbImg = thumbImg;
    }

    public Integer getImg() {
        return img;
    }

    public void setImg(Integer img) {
        this.img = img;
    }

    public String getPackName() {
        return packName;
    }

    public void setPackName(String packName) {
        this.packName = packName;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDesc() {
        return desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
