package com.coinbkt.medmyth.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "PACKS".
 */
@Entity
public class Packs {

    @Id(autoincrement = true)
    private Long id;
    private Integer idPack;
    private String packName;
    private Integer packPoints;
    private Integer packImage;
    private String packStatus;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Packs() {
    }

    public Packs(Long id) {
        this.id = id;
    }

    @Generated
    public Packs(Long id, Integer idPack, String packName, Integer packPoints, Integer packImage, String packStatus) {
        this.id = id;
        this.idPack = idPack;
        this.packName = packName;
        this.packPoints = packPoints;
        this.packImage = packImage;
        this.packStatus = packStatus;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getIdPack() {
        return idPack;
    }

    public void setIdPack(Integer idPack) {
        this.idPack = idPack;
    }

    public String getPackName() {
        return packName;
    }

    public void setPackName(String packName) {
        this.packName = packName;
    }

    public Integer getPackPoints() {
        return packPoints;
    }

    public void setPackPoints(Integer packPoints) {
        this.packPoints = packPoints;
    }

    public Integer getPackImage() {
        return packImage;
    }

    public void setPackImage(Integer packImage) {
        this.packImage = packImage;
    }

    public String getPackStatus() {
        return packStatus;
    }

    public void setPackStatus(String packStatus) {
        this.packStatus = packStatus;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
